language: minimal
sudo: required
services:
  - docker
install:
  - gem install travis --no-rdoc --no-ri
matrix:
  fast_finish: true
env:
  - TEST_TYPE=bazel.release
  - TEST_TYPE=bazel.asan
  - TEST_TYPE=bazel.coverage
  - TEST_TYPE=check_format
  - TEST_TYPE=docs
  - TEST_TYPE=build_image
script: ./ci/ci_steps.sh

branches:
  only:
    - master
